image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - dotnet build SpeakerMeet.sln 
test-job:
    stage: test
    script:
    - dotnet test SpeakerMeet.sln
